export const REGISTER_USER = 'REGISTER_USER';
export const LOCATION_AND_ADDRESS_CHANGE = 'LOCATION_AND_ADDRESS_CHANGE';
export const OTP_SIGNIN = 'OTP_SIGNIN';
export const SIGNOUT = 'SIGNOUT';
export const CHECK_AUTH_STATE = 'CHECK_AUTH_STATE';
